DATA:
  ROOT: 'data_root'
  TRAIN_SUBSET: 'train'
  EVAL_SUBSET: 'val'
  TYPE: 'weekly'
  RESIZE: 512
  NUM_WORKERS: 4
  NUM_CLASSES: 6
  IGNORE_INDEX: -1
TRAINING:
  EPOCHS: 200
  BATCH_SIZE: 4
  LR: 0.0001
  LR_USE_DECAY: False
  LR_DECAY_FACTOR: 0.0
  LR_DECAY_STEP: 0
  WEIGHT_DECAY: 0
  ADAM_B1: 0.5
  ADAM_B2: 0.999
EVALUATION:
  BATCH_SIZE: 1
NETWORK:
  NAME: 'unet3d'
  INPUT_CHANNELS: 4
  OUTPUT_CHANNELS: 6
  LAYER_NUMBER: 3
  FEATURE_CHANNELS: 64
  ENCODER_WIDTHS: [64, 64, 64, 128]
  DECODER_WIDTHS: [32, 32, 64, 128]
  OUT_CONV: [32, 6]
  STR_CONV_K: 4
  STR_CONV_S: 2
  STR_CONV_P: 1
  AGG_MODE: 'att_group'
  ENCODER_NORM: 'group'
  N_HEAD: 16
  D_MODEL: 256
  D_K: 4
  PADDING_MODE: 'reflect'
  PAD_VALUE: 0
LOSS:
  TYPE: 'cross-entropy'
  TOPK: 1.0
  IGNORE_INDEX: -1